import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en" className={GeistSans.className} suppressHydrationWarning>
        <body
            className="bg-gradient-to-b from-white to-orange-50 text-foreground antialiased"
        >
            <div className="w-full px-4 md:px-4 lg:px-4 xl:px-4 2xl:px-4">
                <Navbar />
            </div>
            <div className="px-4 md:px-4 lg:px-4 xl:px-4 2xl:px-4">
                {children}
            </div>
        </body>
        </html>
    </ClerkProvider>
  );
}
